### ISSUE TITLE
Add verification code

### ISSUE THREAD

**Issue by alien0matic** [dkunzler/masterpassword#11]
It is pretty easy to misstype the masterpassword and get the wrong passwords if you've choosen to hide the passwords. It would be good if there would be a verification code (a generated password, that is readable, but the rest is hidden) to know that the correct masterpassword has been entered.

**Comment by dkunzler** [comment]
There is an option to verify the master password at login. I know what you're after, but for now you can use this as a workaround.

**Comment by alien0matic** [comment]
But that way the password will be stored, which makes one of the points of masterpassword obsolete.

**Comment by dkunzler** [comment]
As I said, I know what you're really after, and I think about implementing it, since it is a nice idea to have such a mechanism.

**Comment by dkunzler** [comment]
Implemented with nice graphics on the login screen.
Version 1.5.2
