### ISSUE TITLE
Unlock through Yubikey Neo/NFC

### ISSUE THREAD

**Issue by alien0matic** [dkunzler/masterpassword#12]
It would be great if the app would be unlockable through NFC for example with the Yubikey Neo.
https://www.yubico.com/products/yubikey-hardware/yubikey-neo/

**Comment by dkunzler** [comment]
I don't know how to integrate this concept. Do you want to make a suggestion?

A password is definately necessary to use the algorithm.
What do you want to do using the Yubikey? Store the password encrypted and unlock completely with yubikey?

**Comment by dkunzler** [comment]
No response. Since I have no idea about a use-case I close this now. Feel free to reopen and comment if you have more insights.
