### ISSUE TITLE
insert new domain, disable autocomplete

### ISSUE THREAD

**Issue by brightdroid** [dkunzler/masterpassword#13]
When I insert a new domain, the keyboard (Swiftkey) will always try to autocomplete the domain, which does obviously not work for domains ;)

I've a Nexus 5 - Stock (root) with all updates

**Comment by dkunzler** [comment]
Hi,
I already use the definition `android:inputType="textNoSuggestions"` in the layout to prevent autocorrecting with the default keyboard. Seems that swiftkey will ignore this. I will look into it, if there is a possibility to suppress this on swiftkey, too.

**Comment by dkunzler** [comment]
Ok, this is indeed a case where swiftkey ignores this property:
http://stackoverflow.com/a/21047514

I will try the workaorund suggested in this answer. (However I don't like it)

**Comment by brightdroid** [comment]
Oh ok, didn't know it's actually swiftkeys fault, though it would be great if could add the workaround :)

**Comment by dkunzler** [comment]
since it's a one-liner and doesn't do any harm to non-swiftkey users I'll integrate it ;)

**Comment by brightdroid** [comment]
Great thanks :)

**Comment by brightdroid** [comment]
Thanks, fixed in v1.5 :)
