### ISSUE TITLE
Use courier or other monospaced font to display passwords

### ISSUE THREAD

**Issue by scus1** [dkunzler/masterpassword#16]
The font which is currently used makes it very hard to distinguish O's (oh) and 0's (zero) and I's (capital i) and l's (lowercase L)...

Regards
scus1

**Comment by dkunzler** [comment]
On the main page a serif font is used which allows perfect distinction between i and L. And I think distinction between 0 and O is not that hard with this font. On the detail page of the sites I forgot to use this font, do you mean at this place?

**Comment by scus1** [comment]
Oh, yeah, I mean on the detail page. Didn't realize that it was a different font on the list.

**Comment by dkunzler** [comment]
;)
The view of the password on the detail page came later to the app and I forgot to use the same font as in the list.

**Comment by dkunzler** [comment]
Fix is implemented. Will be in the next version.
