### ISSUE TITLE
mpsites export crashes master password pro

### ISSUE THREAD

**Issue by stesachse** [dkunzler/masterpassword#19]
relevant part from logcat: [logcat-de.devland.masterpassword.pro-2016-06-25.txt](https://github.com/dkunzler/masterpassword/files/332935/logcat-de.devland.masterpassword.pro-2016-06-25.txt)

`java.lang.IllegalArgumentException: GeneratedMaximum:Password is not a constant in com.lyndir.masterpassword.MPSiteType`

**Comment by dkunzler** [comment]
Should work in 1.9.0
APK is downloadable
Play Store Version should be available in a few hours.

Thanks for your report!

**Comment by stesachse** [comment]
it still crashes on export

> java.util.IllegalFormatConversionException: %d can't format com.google.common.primitives.UnsignedInteger arguments

logcat: [logcat-de.devland.masterpassword.pro-2016-06-27.txt](https://github.com/dkunzler/masterpassword/files/334897/logcat-de.devland.masterpassword.pro-2016-06-27.txt)
