### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by Lionirdeadman** [dkunzler/masterpassword#23]
I think it'd be great if this was on F-droid!

(Here for how https://f-droid.org/en/contribute/)

**Comment by dkunzler** [comment]
Sorry, I forgot to answer. Currently I don't plan to publish to other stores. However I will draft a release here in GitHub under Releases. (If I don't forget) So you can download the apk from here.

**Comment by supernatural30** [comment]
Would you be opposed to getting in @IzzySoft repo?

I don't have a gitlab account (yet) but it looks like an issue can be opened to request inclusion.

Inclusion criteria listed on this page:
https://gitlab.com/IzzyOnDroid/repo

**Comment by IzzySoft** [comment]
[This one](https://apt.izzysoft.de/packages/de.devland.masterpassword/)?

**Comment by supernatural30** [comment]
> [This one](https://apt.izzysoft.de/packages/de.devland.masterpassword/)?

My mistake. I just realized it does allow me to download in Droidify if I choose incompatible versions. It says it's incompatible with arm64-v8a


It runs fine on my device so maybe the dev can address compatibility if needed.

Edit: it looks like the Play store version was updated recently but I believe it is the same version number. It looks like that one shows it is compatible with my device. I understand the Dev said he doesn't have much time to work on this project right now anyway. I might open a separate issue later regarding a new APK on GitHub.

**Comment by IzzySoft** [comment]
> My mistake.

Not a mistake; I just added that after your ping :wink:

> It says it's incompatible with arm64-v8a

You've got a Pixel 7+ (or some other arm64-only device)? Then you'll have to wait until the app becomes available at F-Droid.org. For my repo, I can only pick a single APK per app and release, and have a size limit (30 MB per app) in place as the repo runs on my personal space. So I usually pick the armv7a build as that's giving the most widely support. Would I take the arm64, I'd lock out all 32bit devices which I do not want (I'm pro longevity and sustainability; one should be able to use a device as long as possible).

**Comment by supernatural30** [comment]
> > My mistake.
> 
> Not a mistake; I just added that after your ping 😉
> 
> > It says it's incompatible with arm64-v8a
> 
> You've got a Pixel 7+ (or some other arm64-only device)? 

Thanks Izzy. I always appreciate your help (I have donated some Bitcoin to you in the past to let you know, besides with only words, how much I appreciate what you do for the FOSS community and for providing your generous repository).

I have a Samsung Galaxy A53. I don't know if it's arm64-v8a only, or how any of that really works to be honest. It looks like there is only one APK in the releases section of this app, and that works fine on my phone. So if that's armv7a then I suppose my phone can handle it okay.

**Comment by IzzySoft** [comment]
Bitcoin: Ah, thanks! I should take a look at my HODL from time to time :see_no_evil: And thanks for the kind words!

As for the APK: That should then be the very same used in my repo. Very strange. But then, [DeviceSpecs](https://www.devicespecifications.com/de/model/9e9858f6) only mention Armv8 (which would be 64bit AFAIK), not armeabi. Well, if you want to make sure you could have my [Adebar](https://codeberg.org/izzy/Adebar) tell you (or simply run `adb shell getprop ro.product.cpu.abilist`).

> So if that's armv7a then I suppose my phone can handle it okay.

Funnily, from what I see in its `lib/` folder I'd have said it's amd64 (there's just a `x86_64` folder). And even `aapd dump badging` confirms this, saying `native-code: 'x86_64'`). And to top that confusion: the only file in that folder is a library for a Mac (`libscrypt.dylib`). Afraid we need @dkunzler to solve that riddle…

**Comment by dkunzler** [comment]
To avoid confusion I just published 1.14.1 here on github. This should be equal to the version in the playstore but with a higher version number.

It shouldn't contain any native libs anymore.

Hope this helps for a while?

Also I'm so sorry to not being that active here anymore but I really can't find the time between job, kids and renovating a house.

**Comment by supernatural30** [comment]
@dkunzler no apologies needed. You have already done more than most can (or will) do. And as long as the source code stays here then others with the know-how can also contribute.Thanks again for everything, and best wishes on your family and home.

**Comment by IzzySoft** [comment]
Thanks a lot, David! New version will be live in my repo with the next sync (around 6 pm UTC). And as @urmomseksy already wrote: no complaints, just the opposite: best wishes and thanks!
