### ISSUE TITLE
Use androids share feature

### ISSUE THREAD

**Issue by brightdroid** [dkunzler/masterpassword#7]
So, you can share the URL/domain from the browser with the mpw app.
I think of an floating dialog where the URL is prefilled from the browser. 
There should be an option in the settings to select which part of the URL should be used.

**Comment by dkunzler** [comment]
Share feature is added. At the moment not configurable and no floating window. What do you think at this time?

**Comment by brightdroid** [comment]
Looks good, but it's not working when the domain contains a "-"

**Comment by dkunzler** [comment]
Good catch, will look into it...

**Comment by dkunzler** [comment]
Fix is implemented. Will be in the next version.

**Comment by dkunzler** [comment]
At the moment I don't have any plans to make this option more configurable. If there are more people begging for it (or someone opens a pull request) I can add settings for that.
